version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sql_server
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
      TZ: Asia/Bangkok
    ports:
      - "1499:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
      - ./agent:/var/opt/sqlserver-agent
    networks:
      - sqlnet

volumes:
  dbdata:

networks:
  sqlnet: